<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/laptop13.glb --transform --types --draco
-->

<script lang="ts">
  import * as THREE from 'three'
  import { MathUtils } from 'three';

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
	import { roughness } from 'three/tsl';

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Box006: THREE.Mesh
      Box007: THREE.Mesh
      keyboard001: THREE.Mesh
      Rectangle003: THREE.Mesh
      Mesh001: THREE.Mesh
      Mesh001_1: THREE.Mesh
      Mesh001_2: THREE.Mesh
    }
    materials: {
      corpus: THREE.MeshStandardMaterial
      black_plastic: THREE.MeshStandardMaterial
      corpus_silver: THREE.MeshStandardMaterial
      Material29: THREE.MeshStandardMaterial
    }
  }

  const dracoLoader = useDraco();
  const gltf = useGltf<GLTFResult>('/models/laptop13.glb', {dracoLoader})
  const backMaterial = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color(0x666666),
    roughness: 0.35
  });
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 0, -1.88]}
      scale={0.02}
      rotation.y={MathUtils.degToRad(180)}
    >
      <T.Group position={[-0.23, -94.85, 8.95]}>
        <T.Mesh
          geometry={gltf.nodes.Box006.geometry}
          material={backMaterial}
          position={[0, -3.2, 2.03]}
          rotation={[0.01, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.Box007.geometry}
          material={gltf.materials.black_plastic}
          position={[109.6, 1.01, 13.24]}
          rotation={[0.01, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.keyboard001.geometry}
          material={gltf.materials.black_plastic}
          position={[0.48, 2.77, -28.35]}
          rotation={[0.01, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.Rectangle003.geometry}
          material={gltf.materials.corpus_silver}
          position={[0.48, 2.93, -28.35]}
          rotation={[0.01, 0, 0]}
        />
      </T.Group>
      <T.Group position={[0, 1.3, -95.71]}>
        <T.Group
          position={[105.59, -94.69, 8.71]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <T.Mesh
            geometry={gltf.nodes.Mesh001.geometry}
            material={backMaterial}
          />
          <T.Mesh
            geometry={gltf.nodes.Mesh001_1.geometry}
            material={gltf.materials.Material29}
          />
          <T.Mesh
            geometry={gltf.nodes.Mesh001_2.geometry}
            material={gltf.materials.black_plastic}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
