<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/galaxys24.glb --draco --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { MeshPhysicalMaterial } from 'three';
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  import { colorDevices } from './variantes';

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    colorDevice,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    colorDevice: number
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube_1: THREE.Mesh
      Cube_2: THREE.Mesh
      Cube_3: THREE.Mesh
      Cube_4: THREE.Mesh
      Cube_5: THREE.Mesh
      Cube_6: THREE.Mesh
      Cube_7: THREE.Mesh
      Cube_8: THREE.Mesh
      Cube_9: THREE.Mesh
      Cube_10: THREE.Mesh
      Cube_11: THREE.Mesh
      Cube_12: THREE.Mesh
      Cube_13: THREE.Mesh
      Cube_14: THREE.Mesh
      Cube_15: THREE.Mesh
      Cube_16: THREE.Mesh
      Cube_17: THREE.Mesh
      Sphere: THREE.Mesh
      Sphere001: THREE.Mesh
      Sphere002: THREE.Mesh
      Sphere003: THREE.Mesh
      Sphere004: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      superficie: THREE.MeshStandardMaterial
      ['Material.004']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshPhysicalMaterial
      ['Material.007']: THREE.MeshPhysicalMaterial
      ['Material.009']: THREE.MeshStandardMaterial
      ['Material.010']: THREE.MeshStandardMaterial
      ['Material.011']: THREE.MeshStandardMaterial
      ['Material.008']: THREE.MeshStandardMaterial
      ['Material.012']: THREE.MeshStandardMaterial
      ['Material.013']: THREE.MeshPhysicalMaterial
      ['Material.014']: THREE.MeshStandardMaterial
      ['Material.015']: THREE.MeshStandardMaterial
      ['Material.017']: THREE.MeshStandardMaterial
      ['Material.018']: THREE.MeshStandardMaterial
      ['Material.016']: THREE.MeshPhysicalMaterial
    }
  }

  let materialSuperficie = $derived(new MeshPhysicalMaterial({
    color:colorDevices[colorDevice].color, 
    roughness: colorDevices[colorDevice].roughness,
    metalness: colorDevices[colorDevice].metalness
  }));

  const dracoLoader = useDraco();
  const gltf = useGltf<GLTFResult>('/models/galaxys24-transformed.glb', {dracoLoader})
</script>

<T.Group
  bind:ref
  dispose={false}
  position.z={-0.27}
  position.x={0.2}
  scale={100}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[Math.PI, 0, Math.PI]}>
      <T.Mesh
        geometry={gltf.nodes.Cube_1.geometry}
        material={gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_2.geometry}
        material={gltf.materials['Material.002']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_3.geometry}
        material={materialSuperficie}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_4.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_5.geometry}
        material={gltf.materials['Material.005']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_6.geometry}
        material={gltf.materials['Material.006']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_7.geometry}
        material={gltf.materials['Material.007']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_8.geometry}
        material={gltf.materials['Material.009']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_9.geometry}
        material={gltf.materials['Material.010']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_10.geometry}
        material={gltf.materials['Material.011']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_11.geometry}
        material={gltf.materials['Material.008']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_12.geometry}
        material={gltf.materials['Material.012']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_13.geometry}
        material={gltf.materials['Material.013']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_14.geometry}
        material={gltf.materials['Material.014']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_15.geometry}
        material={gltf.materials['Material.015']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_16.geometry}
        material={gltf.materials['Material.017']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_17.geometry}
        material={gltf.materials['Material.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Sphere.geometry}
        material={gltf.materials['Material.016']}
        scale={0}
      />
      <T.Mesh
        geometry={gltf.nodes.Sphere001.geometry}
        material={gltf.materials['Material.016']}
        scale={0}
      />
      <T.Mesh
        geometry={gltf.nodes.Sphere002.geometry}
        material={gltf.materials['Material.016']}
        scale={0}
      />
      <T.Mesh
        geometry={gltf.nodes.Sphere003.geometry}
        material={gltf.materials['Material.016']}
        scale={0}
      />
      <T.Mesh
        geometry={gltf.nodes.Sphere004.geometry}
        material={gltf.materials['Material.016']}
        scale={0}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
