<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/ipad3.glb --draco --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { MeshPhysicalMaterial } from 'three';
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  import { colorDevices } from './variantes';

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    colorDevice,
    ...props
  }: Props<THREE.Group> & {
    colorDevice: number
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Mesh033: THREE.Mesh
      Mesh033_1: THREE.Mesh
      Mesh033_2: THREE.Mesh
      Mesh033_3: THREE.Mesh
      Mesh033_4: THREE.Mesh
      Mesh033_5: THREE.Mesh
      Mesh033_6: THREE.Mesh
    }
    materials: {
      superficie: THREE.MeshStandardMaterial
      ['02 - Default.001']: THREE.MeshStandardMaterial
      ['14 - Default.001']: THREE.MeshStandardMaterial
      ['20 - Default.001']: THREE.MeshStandardMaterial
      cristal: THREE.MeshStandardMaterial
      ['body line.001']: THREE.MeshStandardMaterial
    }
  }

  let materialSuperficie = $derived(new MeshPhysicalMaterial({
    color:colorDevices[colorDevice].color, 
    roughness: colorDevices[colorDevice].roughness,
    metalness: colorDevices[colorDevice].metalness
  }));

  const dracoLoader = useDraco();
  const gltf = useGltf<GLTFResult>('/models/ipad3-transformed.glb', {dracoLoader})
</script>

<T.Group
  bind:ref
  dispose={false}
  scale={74}
  position.z={-0.2}
  position.x={0.16}
  position.y={0.2}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[-0.01, -0.01, 0]}
      scale={0.03}
    >
      <T.Mesh
        geometry={gltf.nodes.Mesh033.geometry}
        material={materialSuperficie}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_1.geometry}
        material={gltf.materials['02 - Default.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_2.geometry}
        material={gltf.materials['14 - Default.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_3.geometry}
        material={gltf.materials['20 - Default.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_4.geometry}
        material={gltf.materials['14 - Default.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_5.geometry}
        material={gltf.materials.cristal}
      />
      <T.Mesh
        geometry={gltf.nodes.Mesh033_6.geometry}
        material={gltf.materials['body line.001']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
